#
# podman run -v /tmp/.X11-unix:/tmp/.X11-unix \
#	-v /dev/snd:/dev/snd \
#	-v /dev/shm:/dev/shm \
#	-v /etc/machine-id:/etc/machine-id:ro \
#	-e DISPLAY=$DISPLAY \
#	r.spiarh.fr/tor-browser
#
FROM r.spiarh.fr/alpine:latest AS builder
LABEL maintainer="_me@spiarh.fr"

RUN apk add --no-cache curl gnupg

# https://www.torproject.org/projects/torbrowser.html.en
ENV TOR_VERSION 10.0.16

# download tor and check signature
RUN cd /tmp \
	&& curl -sSOL "https://dist.torproject.org/torbrowser/${TOR_VERSION}/tor-browser-linux64-${TOR_VERSION}_en-US.tar.xz" \
	&& curl -sSOL "https://www.torproject.org/dist/torbrowser/${TOR_VERSION}/tor-browser-linux64-${TOR_VERSION}_en-US.tar.xz.asc" \
	&& export GNUPGHOME="$(mktemp -d)" \
    && gpg --auto-key-locate nodefault,wkd --locate-keys torbrowser@torproject.org \
    && gpg --output ./tor.keyring --export 0xEF6E286DDA85EA2A4BA7DE684E2C6E8793298290 \
    && gpg --verify tor-browser-linux64-${TOR_VERSION}_en-US.tar.xz.asc tor-browser-linux64-${TOR_VERSION}_en-US.tar.xz \
	&& tar -vxJ --strip-components 1 -C /usr/local/bin -f tor-browser-linux64-${TOR_VERSION}_en-US.tar.xz \
	&& rm -rf tor-browser* "$GNUPGHOME"

FROM r.spiarh.fr/ubuntu:20.04

LABEL maintainer="_me@spiarh.fr"

COPY --from=builder /usr/local/bin /usr/local/bin

RUN apt-get update && apt-get install -y \
	ca-certificates \
	file \
	libasound2 \
	libdbus-glib-1-2 \
	libgtk-3-0 \
	libxrender1 \
	libx11-xcb-dev \
	libx11-xcb1 \
	libxt6 \
	--no-install-recommends && \
    rm -rf /var/lib/apt/lists/* && \
    chown -Rf regular:regular /usr/local/bin

ENV HOME /home/regular
ENV LANG C.UTF-8

WORKDIR $HOME
USER regular

ENTRYPOINT ["/bin/bash"]
CMD ["/usr/local/bin/Browser/start-tor-browser", "--log", "/dev/stdout", "--verbose"]
