ARG FROM_IMAGE_BUILDER
ARG FROM_IMAGE

FROM ${FROM_IMAGE_BUILDER} AS builder

ARG VERSION

RUN apk add --no-cache git make curl gcc libc-dev ncurses

RUN curl -OL "https://github.com/gopasspw/gopass/archive/v${VERSION}.tar.gz" && \
    tar zxf "v${VERSION}.tar.gz" && cd "gopass-${VERSION}" && \
    make build && mv ./gopass /go/bin/gopass

FROM ${FROM_IMAGE}

LABEL maintainer="_me@spiarh.fr"

COPY --from=builder /go/bin/gopass /usr/local/bin/gopass

RUN apk add --no-cache gnupg xclip bash && \
    gopass completion bash > /root/.bashrc

WORKDIR /root

ENTRYPOINT ["/usr/local/bin/gopass"]
