---
- name: check_if_secrets_encrypted
  lineinfile:
    path: "{{ kubeconfig.local_path }}"
    regexp: '^\$ANSIBLE_VAULT.*AES256$'
    state: absent
  run_once: True
  check_mode: yes
  changed_when:
    - secrets_encrypted.found == 0
  register: secrets_encrypted

- debug:
    msg: "{{ secrets_encrypted }}"

# set back to writeable before encrypt if it was set to RO before
- name: change_secrets_perm_before_encrypt
  file:
    path: "{{ kubeconfig.local_path }}"
    mode: 0600
  run_once: True
  when: secrets_encrypted.changed == true

- name: encrypt_secrets
  shell: ansible-vault encrypt "{{ kubeconfig.local_path }}"
  run_once: True
  when: secrets_encrypted.changed == true
