---
- name: check_kubeconfig_path_exist
  stat:
    path: "{{ kubeconfig.path }}"
  register: kubeconfig_path

- name: fetch_admin_conf
  fetch:
    src: "{{ kubeconfig.path }}"
    dest: "{{ kubeconfig.local_path }}"
    mode: '0600'
    flat: yes
  when:
    - kubeconfig_path.stat.exists == true
