kind: ConfigMap
apiVersion: v1
metadata:
  name: kubernetes-services-endpoint
  namespace: kube-system
data:
  KUBERNETES_SERVICE_HOST: "{{ kubernetes.control_plane_endpoint.split(":")[0] }}"
  KUBERNETES_SERVICE_PORT: "{{ kubernetes.control_plane_endpoint.split(":")[1] }}"
