image:
  registry: r.spiarh.fr/library
  name: hugo
  tag: 0.85.0
spec:
  fromImages:
  - registry: docker.io/library
    name: golang
    tag: 1.16-alpine
    target: builder
  - registry: r.spiarh.fr/library
    name: alpine
    tag: 3.14.0
  buildArgs:
  - VERSION
  tagFormat: '{{ .VERSION }}'
  facts:
  - name: VERSION
    value: 0.85.0
    source: github
    kind: version
  sources:
  - name: github
    github:
      owner: gohugoio
      repository: hugo
      object: release
