ARG FROM_IMAGE_DOWNLOADER

FROM ${FROM_IMAGE_DOWNLOADER} AS downloader

ARG VERSION
ARG BASE_URL=https://partner-images.canonical.com/core/${VERSION}/current/
ARG DIST=ubuntu-${VERSION}-core-cloudimg-amd64-root.tar.gz
ARG DIST_DIR=/dist
ARG RELEASE=${BASE_URL}/${DIST}
ARG RELEASE_SHA256=${BASE_URL}/SHA256SUMS

RUN wget -O $DIST $RELEASE && \
    wget -q -O- $RELEASE_SHA256 | grep $DIST | sha256sum -c - && \
    mkdir -p ${DIST_DIR} && \
    tar -xf $DIST -C ${DIST_DIR}

FROM scratch

LABEL maintainer="_me@spiarh.fr"

ARG DIST_DIR=/dist

COPY --from=downloader ${DIST_DIR} /

# a few minor container specific tweaks
# see https://github.com/docker/docker/blob/9a9fc01af8fb5d98b8eec0740716226fadb3735c/contrib/mkimage/debootstrap
RUN set -xe \
	\
# https://github.com/docker/docker/blob/9a9fc01af8fb5d98b8eec0740716226fadb3735c/contrib/mkimage/debootstrap#L40-L48
	&& echo '#!/bin/sh' > /usr/sbin/policy-rc.d \
	&& echo 'exit 101' >> /usr/sbin/policy-rc.d \
	&& chmod +x /usr/sbin/policy-rc.d \
	\
# https://github.com/docker/docker/blob/9a9fc01af8fb5d98b8eec0740716226fadb3735c/contrib/mkimage/debootstrap#L54-L56
	&& dpkg-divert --local --rename --add /sbin/initctl \
	&& cp -a /usr/sbin/policy-rc.d /sbin/initctl \
	&& sed -i 's/^exit.*/exit 0/' /sbin/initctl \
	\
# https://github.com/docker/docker/blob/9a9fc01af8fb5d98b8eec0740716226fadb3735c/contrib/mkimage/debootstrap#L71-L78
	&& echo 'force-unsafe-io' > /etc/dpkg/dpkg.cfg.d/container-apt-speedup \
	\
# https://github.com/docker/docker/blob/9a9fc01af8fb5d98b8eec0740716226fadb3735c/contrib/mkimage/debootstrap#L85-L105
	&& echo 'DPkg::Post-Invoke { "rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true"; };' > /etc/apt/apt.conf.d/container-clean \
	&& echo 'APT::Update::Post-Invoke { "rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true"; };' >> /etc/apt/apt.conf.d/container-clean \
	&& echo 'Dir::Cache::pkgcache ""; Dir::Cache::srcpkgcache "";' >> /etc/apt/apt.conf.d/container-clean \
	\
# https://github.com/docker/docker/blob/9a9fc01af8fb5d98b8eec0740716226fadb3735c/contrib/mkimage/debootstrap#L109-L115
	&& echo 'Acquire::Languages "none";' > /etc/apt/apt.conf.d/container-no-languages \
	\
# https://github.com/docker/docker/blob/9a9fc01af8fb5d98b8eec0740716226fadb3735c/contrib/mkimage/debootstrap#L118-L130
	&& echo 'Acquire::GzipIndexes "true"; Acquire::CompressionTypes::Order:: "gz";' > /etc/apt/apt.conf.d/container-gzip-indexes \
	\
# https://github.com/docker/docker/blob/9a9fc01af8fb5d98b8eec0740716226fadb3735c/contrib/mkimage/debootstrap#L134-L151
	&& echo 'Apt::AutoRemove::SuggestsImportant "false";' > /etc/apt/apt.conf.d/container-autoremove-suggests \
    \
    echo 'Dpkg::Options::="--force-confnew";'> /etc/apt/apt.conf.d/container-noninteractive

RUN apt update && \
    apt -y upgrade && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /usr/local/etc && \
    addgroup --system -gid 1871 regular && \
    adduser --system --uid 1871 --gid 1871 --shell /bin/false --disabled-password regular

ENTRYPOINT ["/bin/bash"]
