---
# tasks file for kubernetes
- name: add_apt_keys
  apt_key:
    url: "{{ item }}"
    state: present
  with_items:
    - "{{ kubernetes.apt_keys }}"

- name: add_apt_repos
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "{{ kubernetes.apt_repos }}"

- name: install_packages
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    update_cache: yes
    dpkg_options: "force-confold,force-confdef,force-hold"
    force: yes
  with_items:
    - "{{ kubernetes.pkgs }}"

- name: apt_mark_packages_hold
  dpkg_selections:
    name: "{{ item.name.split('=')[0] }}"
    selection: hold
  with_items:
    - "{{ kubernetes.pkgs }}"
