---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd
  namespace: runtime
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: editor
subjects:
- kind: ServiceAccount
  name: argocd-argocd-application-controller
  namespace: pipeline
