image:
  registry: r.spiarh.fr/library
  name: nginx
  tag: 1.22.1-r0
spec:
  fromImages:
  - registry: r.spiarh.fr/library
    name: alpine
    tag: 3.16.2
  buildArgs:
  - VERSION
  tagFormat: '{{ .VERSION }}'
  facts:
  - name: VERSION
    value: 1.22.1-r0
    source: alpine
    kind: version
  sources:
  - name: alpine
    alpine:
      package: nginx
      repository: main
      versionId: "3.16"
      arch: x86_64
      mirror: http://dl-cdn.alpinelinux.org
