image:
  registry: r.spiarh.fr/library
  name: reg
  tag: 0.16.1
spec:
  fromImages:
  - registry: docker.io/library
    name: golang
    tag: 1.16-alpine
    target: builder
  - registry: r.spiarh.fr/library
    name: alpine
    tag: 3.14.0
  buildArgs:
  - VERSION
  tagFormat: '{{ .VERSION }}'
  facts:
  - name: VERSION
    value: 0.16.1
    source: reg
    kind: version
  sources:
  - name: reg
    github:
      owner: genuinetools
      repository: reg
      object: release
