---
- include_tasks: join/copy_conf.yml
- include_tasks: reset.yml
# reimport cert wipe by kubeadm reset...
- import_tasks: certs.yml
- include_tasks: patches.yml
- import_tasks: secret_encryption.yml
  when:
    - inventory_hostname in groups['masters']
    - kubernetes.apiserver.secret_encryption.enabled
- include_tasks: kube-vip.yml
  when:
    - inventory_hostname in groups['masters']
    - kube_vip.enabled

- name: run_kubeadm_join
  command: "kubeadm join --config {{ kubeadm.join.config_file }} -v{{ kubeadm.log_level }}"
  notify: create_join_witness_file
  register: run_kubeadm_join

- debug:
    var: run_kubeadm_join

- meta: flush_handlers

- include_tasks: join/check.yml
  when: run_kubeadm_join is succeeded

- include_tasks: join/rm_conf.yml
