---
- name: copy_etcd_secret_entryption
  template:
    src: "encryption-provider-config.yaml.j2"
    dest: "{{ kubernetes.apiserver.secret_encryption.path }}"
    owner: root
    group: root
    mode: 0400
