image:
  registry: r.spiarh.fr/library
  name: stern
  tag: 1.19.0
spec:
  fromImages:
  - registry: docker.io/library
    name: golang
    tag: "1.16"
    target: builder
  - registry: r.spiarh.fr/library
    name: alpine
    tag: 3.14.0
  buildArgs:
  - VERSION
  tagFormat: '{{ .VERSION }}'
  facts:
  - name: VERSION
    value: 1.19.0
    source: github
    kind: version
  sources:
  - name: github
    github:
      owner: stern
      repository: stern
      object: release
