ARG FROM_IMAGE_BUILDER
ARG FROM_IMAGE

FROM ${FROM_IMAGE_BUILDER} AS builder

ARG VERSION

RUN apt update && apt install unzip

RUN curl -OL "https://github.com/stern/stern/archive/v${VERSION}.zip" && \
    unzip "v${VERSION}.zip" && cd "stern-${VERSION}" && \
    CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-extldflags "-static"' -o dist/stern . && mv dist/stern /go/bin/stern
    # make build && mv dist/stern /go/bin/stern

FROM ${FROM_IMAGE}

LABEL maintainer="_me@spiarh.fr"

COPY --from=builder /go/bin/stern /usr/local/bin/stern

ENTRYPOINT ["/usr/local/bin/stern"]
