ARG FROM_IMAGE_BUILDER
ARG FROM_IMAGE

FROM ${FROM_IMAGE_BUILDER} AS builder

ARG VERSION

RUN curl -OL "https://github.com/google/go-containerregistry/archive/v${VERSION}.tar.gz" && \
    tar zxf "v${VERSION}.tar.gz" && cd "go-containerregistry-${VERSION}" && \
    CGO_ENABLED=0 go install -a -ldflags '-extldflags "-static"' ./cmd/crane && \
    CGO_ENABLED=0 go install -a -ldflags '-extldflags "-static"' ./cmd/gcrane && \
    CGO_ENABLED=0 go install -a -ldflags '-extldflags "-static"' ./cmd/registry

FROM ${FROM_IMAGE}

LABEL maintainer="_me@spiarh.fr"

COPY --from=builder /go/bin/crane /usr/local/bin/crane
COPY --from=builder /go/bin/gcrane /usr/local/bin/gcrane
COPY --from=builder /go/bin/registry /usr/local/bin/registry

ENTRYPOINT ["sh", "-c"]
